backend:
  name: github
  repo: ryanradosevich87-lab/Personal-website
  branch: main
  base_url: https://customwebportfolio.netlify.app
  auth_endpoint: /auth

media_folder: "content/photos"
public_folder: "/content/photos"

collections:
  - name: "stories"
    label: "Works"
    folder: "content/stories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "essays"
    label: "Essays"
    folder: "content/essays"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "photos"
    label: "Pictures"
    folder: "content/photos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Caption", name: "body", widget: "markdown"}
